name: Mirror to Giltab
on:
  push:
  delete:
  create:
  workflow_dispatch:
  
jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:                                            
      - uses: actions/checkout@v1
      - uses: kankanNB/mirror-action@master
        with:
          REMOTE: '${{ secrets.GITLAB }}/cicd/myflag.git'
          GIT_USERNAME: root
          GIT_PASSWORD: ${{ secrets.PASSWORD }}
